package collector

import (
	"bloodhound-kube/internal/utils"
)

// AllHandlers defines all available resource handlers with their metadata
// This is the single source of truth for all collectors in the system.
// To add a new collector:
// 1. Add the collection function to collectors.go
// 2. Add a metadata entry here
var AllHandlers = []HandlerMetadata{
	{
		Name:                  "nodes",
		Nicknames:             []string{"no", "node"},
		ResourceType:          "node",
		Description:           "Collect Kubernetes nodes",
		ClusterScoped:         true,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectNodes,
	},
	{
		Name:                  "secrets",
		Nicknames:             []string{"sec", "secret"},
		ResourceType:          "secret",
		Description:           "Collect Kubernetes secrets",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectSecrets,
	},
	{
		Name:                  "configmaps",
		Nicknames:             []string{"cm", "configmap"},
		ResourceType:          "configmap",
		Description:           "Collect Kubernetes configmaps",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectConfigMaps,
	},
	{
		Name:                  "deployments",
		Nicknames:             []string{"deploy", "deployment"},
		ResourceType:          "deployment",
		Description:           "Collect Kubernetes deployments",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectDeployments,
	},
	{
		Name:                  "services",
		Nicknames:             []string{"svc", "service"},
		ResourceType:          "service",
		Description:           "Collect Kubernetes services",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectServices,
	},
	{
		Name:                  "ingresses",
		Nicknames:             []string{"ing", "ingress"},
		ResourceType:          "ingress",
		Description:           "Collect Kubernetes ingresses",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectIngresses,
	},
	{
		Name:                  "gateways",
		Nicknames:             []string{"gw", "gateway"},
		ResourceType:          "gateway",
		Description:           "Collect Kubernetes gateways",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectGateways,
	},
	{
		Name:                  "rbac",
		Nicknames:             []string{},
		ResourceType:          "rbac",
		Description:           "Collect Kubernetes RBAC resources",
		ClusterScoped:         true,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectRBAC,
	},
	{
		Name:                  "networkpolicies",
		Nicknames:             []string{"netpol", "networkpolicy", "netpols"},
		ResourceType:          "networkpolicy",
		Description:           "Collect Kubernetes network policies",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectNetworkPolicies,
	},
	{
		Name:                  "crds",
		Nicknames:             []string{"crd"},
		ResourceType:          "crd",
		Description:           "Collect Kubernetes custom resource definitions",
		ClusterScoped:         true,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectCRDs,
	},
	{
		Name:                  "daemonsets",
		Nicknames:             []string{"ds", "daemonset"},
		ResourceType:          "daemonset",
		Description:           "Collect Kubernetes daemonsets",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectDaemonSets,
	},
	{
		Name:                  "statefulsets",
		Nicknames:             []string{"sts", "statefulset"},
		ResourceType:          "statefulset",
		Description:           "Collect Kubernetes statefulsets",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectStatefulSets,
	},
	// OpenShift-specific handlers
	{
		Name:                  "routes",
		Nicknames:             []string{"route"},
		ResourceType:          "route",
		Description:           "Collect OpenShift routes",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeOpenShift},
		CollectFunc:           collectRoutes,
	},
	{
		Name:                  "projects",
		Nicknames:             []string{"project"},
		ResourceType:          "project",
		Description:           "Collect OpenShift projects",
		ClusterScoped:         true,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeOpenShift},
		CollectFunc:           collectProjects,
	},
	{
		Name:                  "images",
		Nicknames:             []string{"image"},
		ResourceType:          "image",
		Description:           "Collect OpenShift images",
		ClusterScoped:         true,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeOpenShift},
		CollectFunc:           collectImages,
	},
	{
		Name:                  "pods",
		Nicknames:             []string{"po", "pod"},
		ResourceType:          "pod",
		Description:           "Collect Kubernetes pods",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectPods,
	},
	{
		Name:                  "httproutes",
		Nicknames:             []string{"httproute"},
		ResourceType:          "httproute",
		Description:           "Collect Gateway API HTTPRoutes",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectHTTPRoutes,
	},
	{
		Name:                  "grpcroutes",
		Nicknames:             []string{"grpcroute"},
		ResourceType:          "grpcroute",
		Description:           "Collect Gateway API GRPCRoutes",
		ClusterScoped:         false,
		SupportedClusterTypes: []utils.ClusterType{utils.ClusterTypeKubernetes, utils.ClusterTypeOpenShift},
		CollectFunc:           collectGRPCRoutes,
	},
}
